exp-name: seqc-bgi
reads-dir: /fs/cbcb-lab/rob/students/jason/SEQC-data/SEQC/output-kfold/seqc-bgi/kfold
tx-path: /fs/cbcb-lab/rob/students/jason/shared/annotations/hg19.fa.gz

prior-weights:
  - 1e-6
  - 1e-5
  - 1e-4
  - 1e-3
  - 1e-2
  - 1e-1
  - 1e0
  - 1e1
  - 1e2
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7 
  - 8
  - 9
k: 5

read_file_fmt: fasta

sample-names:
- BGI_FC1_A_1
- BGI_FC1_A_2
- BGI_FC1_A_3
- BGI_FC1_A_4
- BGI_FC1_B_1
- BGI_FC1_B_2
- BGI_FC1_B_3
- BGI_FC1_B_4
- BGI_FC1_C_1
- BGI_FC1_C_2
- BGI_FC1_C_3
- BGI_FC1_C_4
- BGI_FC1_D_1
- BGI_FC1_D_2
- BGI_FC1_D_3
- BGI_FC1_D_4